### ISSUE TITLE
[Startup error] File exists (os error 17)

### ISSUE THREAD

**Issue by Bigceru** [bewcloud/bewcloud#30] opened 2024-12-08 18:20 UTC
## Error Description
Hi everyone, 

I was trying to start the Docker Compose on my ARM device (Raspberry Pi 4), but I encountered the following error (no other logs are shown):

```
error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
make: *** [Makefile:20: migrate-db] Error 1
```
## My Configuration
Here is my `docker-compose.yml`:

```yaml
services:
  website:
    image: ghcr.io/bewcloud/bewcloud:main
    restart: on-failure
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '256m'
    user: '${UID}:${GID}'
    env_file:
      - path: .env
        required: true
    volumes:
      - /mnt/ExternalHDD/bewCloud:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DBNAME}
    restart: on-failure
    volumes:
      - bewcloud-db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'

volumes:
  bewcloud-db:
    driver: local
```

And my `.env` file:

```env
PORT=8000
BASE_URL="http://localhost:8000"

UID=1000
GID=1000

POSTGRESQL_HOST="*****"
POSTGRESQL_USER="*****"
POSTGRESQL_PASSWORD="*****"
POSTGRESQL_DBNAME="*****"
POSTGRESQL_PORT=5432
POSTGRESQL_CAFILE=""

JWT_SECRET="fake"
PASSWORD_SALT="fake"

BREVO_API_KEY="fake"

CONFIG_ALLOW_SIGNUPS="true"
CONFIG_ENABLED_APPS="news,notes,photos"
CONFIG_FILES_ROOT_PATH="data-files"
CONFIG_ENABLE_EMAILS="false"
CONFIG_ENABLE_FOREVER_SIGNUP="true"
```

## Steps to Reproduce
1. Run `docker compose run website bash -c "cd /app && make migrate-db"` on an ARM device with the configuration above.
2. Observe the error during the startup of the `website` service.

Thank you in advance for your help!

**Comment by BrunoBernardino** [comment] 2024-12-08 19:26
Thank you for reporting this @Bigceru . @ryuuzake can you reproduce this? I don't have an arm device to test. It looks like it's deno-related and it might be better to create an issue there for it.

**Comment by ryuuzake** [comment] 2024-12-08 19:29
Sure @BrunoBernardino. I will try to check on it

**Comment by Bigceru** [comment] 2024-12-14 15:07
**Updates Summary:**
Downgrade Deno version and change configuration; new crash issue with large file uploads.

**Details:**
- Changed Deno base image from `denoland/deno:ubuntu-2.1.2` to `denoland/deno:ubuntu-1.46.3`.
- Updated `deno.json`, modifying `"nodeModulesDir": "auto"` to `"nodeModulesDir": true`.
- After these changes, build the image and edit `docker-compose.yml` in order to use it
- I successfully accessed bewCloud!
- However, uploading large files (e.g., 3GB) causes the application to crash with exit code 0. The service restarts automatically, but the file is not uploaded.

**Comment by BrunoBernardino** [comment] 2024-12-15 07:04
Thanks @Bigceru, it's interesting to learn that downgrading Deno fixed the arm thing. Hopefully that means in a future Deno version the problem will be fixed!

As for the upload error, confirm it's not the proxy rejecting, nor container running out of memory (the default `docker-compose.yml` has memory limits you might want to remove in that case). Check https://github.com/bewcloud/bewcloud/issues/22 for more info.

**Comment by apacheli** [comment] 2024-12-20 05:39
I encountered the same issue running Intel and Ubuntu 24.04:

Docker error log:

```
2024-12-19 23:24:11 error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
2024-12-19 23:25:03 error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
2024-12-19 23:26:05 error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
2024-12-19 23:27:06 error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
2024-12-19 23:28:07 error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
2024-12-19 23:29:09 error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
```

I used the base configuration provided by the README with minimal changes, and `docker compose up -d` to launch it. The Postgres 15 container was working fine though.

**Comment by BrunoBernardino** [comment] 2024-12-20 05:47
Sounds like something with Deno itself (probably related to `node_modules`: "auto"). Does downgrading it work for you?

**Comment by vkhurana** [comment] 2024-12-20 20:56
I'm just pulling the `ghcr.io/bewcloud/bewcloud:main` image, and have the same issue.

I don't think this is related to Arm, since it's also happening on x86

```

bewcloud_srv  | error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
bewcloud_srv exited with code 0
bewcloud_srv  | error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
bewcloud_srv  | error: File exists (os error 17), symlink '../commander@4.1.1/node_modules/commander' -> '/app/node_modules/.deno/node_modules/commander'
bewcloud_srv  | error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'
bewcloud_srv  | error: File exists (os error 17), symlink '../postcss@8.4.49/node_modules/postcss' -> '/app/node_modules/.deno/node_modules/postcss'

```

Bummer, I was looking to get away from nextcloud too.

**Comment by BrunoBernardino** [comment] 2024-12-21 07:21
@vkhurana can you try pulling from v1.4.3 (before the upgrade to Deno 2)? https://github.com/bewcloud/bewcloud/pkgs/container/bewcloud/309818592?tag=v1.4.3

**Comment by vkhurana** [comment] 2024-12-21 15:54
@BrunoBernardino That worked! So this must be related to the Deno 2 upgrade.

I'm not familiar with typescript, but I'll try to see if I can help debug.

**Closed** 2024-12-26 11:54 UTC
Labels: bug, help wanted

**Comment by BrunoBernardino** [comment] 2024-12-26 12:05
@vkhurana / @Bigceru can you please try the latest version and see if the problem's fixed for you? Otherwise I might just try creating an issue in Deno.

**Comment by Bigceru** [comment] 2025-01-05 23:08
@BrunoBernardino I have just cloned the repository, and I stumbled upon the same error.

**Comment by BrunoBernardino** [comment] 2025-01-06 05:31
@Bigceru so not via Docker?

**Comment by kobusestas** [comment] 2025-02-09 05:36
I'm having the same issue on x86 when pulling ghcr.io/bewcloud/bewcloud:main was this ever fixed or what's the recommendation?

**Comment by BrunoBernardino** [comment] 2025-02-09 07:34
@kobusestas I was never able to reproduce this locally or remotely. If you can reproduce it easily, I'd recommend creating an issue in [Deno](https://github.com/denoland/deno)'s or [Fresh](https://github.com/denoland/fresh)'s repo, to try and get some more ideas. Most people with the issue before had it fixed by reducing the `deno` version, which is _OK_, but not really secure going forward.

Here's one solution if you're building it: https://github.com/bewcloud/bewcloud/issues/30#issuecomment-2543146631

The other solution is to pull `ghcr.io/bewcloud/bewcloud:v1.4.3` (before the Deno 2 upgrade).
