### ISSUE TITLE
Ready to run docker container

### ISSUE THREAD

**Issue by Joly0** [bewcloud/bewcloud#5] opened 2024-04-06 20:49 UTC
Hey, i wanted to try bewcloud, but as i cant use make commands etc on my main server, i wanted to give the docker container a try. So i built a container for myself https://hub.docker.com/r/joly0/bewcloud and tried to run it together with a postgres 15 docker container.

So far the container is working and the webui is accessible, though when i try to signup i get this error message:
![grafik](https://github.com/bewcloud/bewcloud/assets/13993216/5201d925-f035-4195-813e-5f560ca87a06)

Could it be, because i access the webui through http? I havent setup any ssl reverse proxy stuff for it, just wanted to give it a quick try.

Other than that, i think it would be a great idea, if there was a ready to run docker container for this, so the docker compose would be complete aswell. If any assistance is needed, i might be able to assist or provide a dockerfile for it

**Comment by BrunoBernardino** [comment] 2024-04-07 05:46
Thanks! I'll address this with #1 as the demo would just deploy the same container, and act as a test, so I'll close this once we can figure out what's up with your setup.

Here's a  `docker-compose.yml` I'm using with this repo which has a `caddy` reverse proxy in front of it for TLS, but should work even without it:

```yaml
services:
  website:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    mem_limit: '256m'
    volumes:
      - ./data-files:/app/data-files

  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=bewcloud
    restart: on-failure
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: '256m'

```

In any case, the error seems related to the postgres connection. 

Does your `.env` file have `POSTGRESQL_CAFILE=""`? That would disable TLS for PostgreSQL.

**Comment by Joly0** [comment] 2024-04-07 20:57
Ok, so i got a step further, i guess it was the ip and port, which were wrong. Had to adjust the .env file, which isnt that easy, if you are in a docker container and no option to install any additional file editor.

But now i got this error:
![grafik](https://github.com/bewcloud/bewcloud/assets/13993216/5dfd983f-0f82-4ec1-b9d9-98e70184a033)

Its probably because the database isnt set up or anything, which makes sense, as i cant/didnt run the "make migrate-db" command, which i guess sets up the database.

I think this should be able to get adressed with a fully working docker container

**Comment by BrunoBernardino** [comment] 2024-04-08 05:01
@Joly0 indeed. You say you can't run it, but if you can simply `docker exec -it <container> sh`, you can then `apk add make` and then run `cd /app && make migrate-db`  to run it.

**Comment by BrunoBernardino** [comment] 2024-04-08 11:20
Oh, you're right, I forgot about that. `docker exec -u root -it <container> sh` should work to become root, or, depending on how it was installed, `sudo docker exec -u root -it <container> sh`, then `apt install make` and finally `cd /app && make migrate-db`.

**Comment by Joly0** [comment] 2024-04-08 13:48
Ok, we are again one step closer. I get this notification now:
![image](https://github.com/bewcloud/bewcloud/assets/13993216/543838b5-e7bc-423a-a8ec-00a20c39854d)

**Comment by BrunoBernardino** [comment] 2024-04-08 16:15
Dang it. I still don't have a good way to disable the whole email thing. I'll need to do that for this to be more easy, but in any case, you should have a `bewcloud_users` row now, and you can make it `status = 'active'`, then just login with the password you tried to signup with.

**Comment by Joly0** [comment] 2024-04-08 18:24
Hm, awkward. I tried exactly what you said, and noticed that the account was already active, i tried to login again, but still the screen above. I saw the "is_email_verified" option under "extra" in the bewcloud_users which was set to false. I set it to true, tried to login again, and the error message disappeared, but nothing happens. The Page loads for a moment, then i end up on the login page again

**Comment by BrunoBernardino** [comment] 2024-04-08 18:32
:thinking: Nothing in `docker compose logs`?

**Comment by BrunoBernardino** [comment] 2024-04-08 18:38
did you change the `BASE_URL` in `.env` to match `http://192.168.178.220:8005`? That would affect the cookie being set. You can also see in your browser's storage if there's any cookie set for that IP address, and there should be one named `bewcloud-app-v1`.

**Comment by Joly0** [comment] 2024-04-08 18:42
![grafik](https://github.com/bewcloud/bewcloud/assets/13993216/81a2b887-53bc-4e63-8e54-7d772728cfe6)
I guess i dont need to change the port variable? But yes, the base_url is correct and still nothing

**Comment by BrunoBernardino** [comment] 2024-04-08 19:17
That looks fine. I'm always using hostnames or domains, so I'd have to spend some time testing that. I just finished [building the desktop sync app](https://github.com/bewcloud/bewcloud-desktop), so I can look into this next and update you throughout the week.

**Comment by BrunoBernardino** [comment] 2024-04-08 19:57
@Joly0 I didn't get a chance to test with IPs yet, but I think I found the cause. Pull down the latest code and let me know if it works for you, logging in (don't forget to update your `.env` with the new two `CONFIG_` variables that are in the `.env.sample`).

**Comment by BrunoBernardino** [comment] 2024-04-09 05:11
@Joly0 you can certainly use the existing database. I just realized the [`Domain` attribute in `Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent) doesn't support IP addresses, so that's the issue. I'll have to not set it when `BASE_URL` is an IP address.

And thanks for letting me know you got it working!

**Comment by BrunoBernardino** [comment] 2024-04-09 12:27
https://github.com/bewcloud/bewcloud/commit/735b14544a48864fe21996b40644b1450ff4dd94 just [published an image](https://github.com/bewcloud/bewcloud/pkgs/container/bewcloud) and [`docker-compose.yml`](https://github.com/bewcloud/bewcloud/blob/735b14544a48864fe21996b40644b1450ff4dd94/docker-compose.yml) for easier self-hosting. Hopefully that helps others in the future set it up more easily!

**Closed by BrunoBernardino** 2024-04-09 12:27 UTC

**Comment by Joly0** [comment] 2024-04-09 18:29
Hey, great thing you got a working docker image ready to run, but there are two things i have noticed. First is the elephant in the room:
`docker: Error response from daemon: Head "https://ghcr.io/v2/bewcloud/bewcloud/manifests/latest": unauthorized`
when i try to pull the image
and the second is regarding the .env file. How is that handled inside the container? I dont see any mount for that file or any option to set the "base_url" variable for example? Can i simply set it through a docker environment variable?

**Comment by BrunoBernardino** [comment] 2024-04-09 19:04
@Joly0 nice catch. I just made it public in visibility, didn't realize it was private by default. As for the `.env` file, I thought it wouldn't be necessary, but you're right, it should be included in the provided `docker-compose.yml`, and it is now!

**Comment by keyxmakerx** [comment] 2024-08-24 23:15
Forgive me for commenting in a closed issue, but i'm getting an error when trying to pull image. 

`Pulling image 
[ERROR] Rolling back changes because of -- Image pull error: invalid reference format`

Is anyone familiar with why it wouldn't be able to pull the image? I'm using the compose example almost verbatim aside from a different directory and POST user info.

**Comment by BrunoBernardino** [comment] 2024-08-25 05:51
No worries, I'm not seeing such problem, but maybe this can help: https://stackoverflow.com/questions/45682010/docker-invalid-reference-format

**Comment by BrunoBernardino** [comment] 2024-09-06 19:20
@keyxmakerx no worries, I appreciate the reply! Feel free to create an issue here so I can try to help!
